### ISSUE TITLE
Card Setup?

### ISSUE THREAD

**Issue by gdreelin** [dylandoamaral/trakt-integration#2]
Once you have it installed how did you setup the card? And can you have both the original sensor one with this one at the same time or does it goof up?

**Comment by dylandoamaral** [comment]
I wrote the readme to explain the process. Maybe it's not clear enough.
To summarise, you first have to add the integration and provide your trakt identifiers (look at the readme for more information).
When your home assistant instance is linked with trakt.tv you then have to provide a yaml configuration to add sensors depending on what kind of media category you want (dvd, premiere etc...).
About the "original sensor", What did you mean, there is no "real sensor" however there are a bunch of sensors for each media category that you choose.
Maybe it didnt work very well, I didnt try it since the integration is in HACS (I am on holliday). If there is any problem I will fix it on September ;).

**Comment by gdreelin** [comment]
No worries I figured it out on the configs and put the information on the other open ticket you had for syntax. Sorry what I meant about the original sensor was there was another Trakt integration out there but found both cannot be working at the same time. I do like your way better than the other.

**Comment by dylandoamaral** [comment]
Hello thanks, I didn't have time to try the integration using HACS yet. I still think you can use both trakt integrations however you have to create two applications in trakt instead of one (just a hypothesis). Feel free to ask for other features and feel free to make a PR if you think the ReadMe can be improved.
