### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Jurgenn22** [dylandoamaral/trakt-integration#5]
Hey,
Is it also possible to add Trakt's collection as a sensor? So you can see new releases for your existing collection of TV shows in Trakt, on the upcomingmedia card.

**Comment by dylandoamaral** [comment]
You already can follow your own TV shows using this integration. However You cant follow a shows from a particular collections since the trakt Api doesnt provide a way to do it. 

It uses calendar from trakt website so if the show appear in your calendar, it should appear on home assistant.

Dont hesitate to reopen this issue if needed.
