### ISSUE TITLE
Login  issue

### ISSUE THREAD

**Issue by thor9898** [dylandoamaral/trakt-integration#69]
I've tried using my custom server adress and with the workaround that is given in the readme.md but after filling up with the credentials it always stays like this:

![image](https://user-images.githubusercontent.com/58491644/223386662-83240c22-624a-4ccd-b997-d25851b4cf10.png)

**Comment by dylandoamaral** [comment]
I don't think this is a trakt integration issue I never saw something like that.

**Comment by dylandoamaral** [comment]
Try to uninstall and install it again from scratch and then ask to the home assistant forum maybe giving as much information as you can such as what is your home assistant version, do you have error logs, what kind of hosting you use (home assistant OS, docker image, serverless) and so on. I don't think this is due to my integration but I can be wrong. If other people have the same issue feel free to comment this issue.
